[general]
import = ["./themes/solarized_dark.toml"]

[keyboard]
bindings = [
  { key = "N", mods = "Control", command = { program = "/usr/bin/alacritty", args = ["msg", "create-window"] } },
  { key = "Q", mods = "Control", action = "ClearLogNotice" },
  { key = "W", mods = "Command", action = "None" }
]

[window]
dimensions = { columns = 80, lines = 24 }

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

# --- Font Settings ---
[font]
size = 14.0

[font.normal]
family = "Terminus"
style = "Regular"

# --- Scrolling ---
[scrolling]
history = 10000
multiplier = 3

# --- Selection ---
[selection]
save_to_clipboard = true


